/**
 * API Communication Layer
 * 
 * CRITICAL: This file handles ONLY communication with backend.
 * NO business logic, NO intent detection, NO routing decisions.
 * 
 * Responsibilities:
 * - Send requests to backend
 * - Receive responses from backend
 * - Type validation
 * - Error handling (network errors only)
 */

import { config } from '@/config';

// ============================================================================
// TYPE DEFINITIONS (Match Backend Contract)
// ============================================================================

export type MessageRole = 'user' | 'assistant';

export interface ChatHistoryItem {
    role: MessageRole;
    content: string;
}

export interface ChatRequest {
    session_id: string;
    current_message: string;
    chat_history: ChatHistoryItem[];
    intent_id?: string; // For pagination/load more (skip classification)
    offset?: number;    // Pagination offset
}

export interface ClarificationResponse {
    response_type: 'clarification';
    intent_id: string;
    confidence: number;
    missing_info: string[];
    clarifying_question: string;
}

// Presentation Layer Product (Generated by LLM 2)
export interface PresentationProduct {
    product_id: string; // From Supabase
    title: string;      // From Supabase
    price: string;      // From Supabase
    image_url: string;  // From Supabase
    description: string; // Generated "Why this fits" (LLM)
    reasoning: string;   // Detailed reasoning (LLM - Primary only)
    features?: string[]; // Generated features list
}

export interface RecommendationResponse {
    response_type: 'recommendation';
    intent_id: string;
    confidence: number;
    primary_recommendation?: PresentationProduct; // Rank 1 (only for first page)
    secondary_recommendations: PresentationProduct[]; // Rank 2-3 (or 4-6 on load more)
    acknowledgement: string; // "I found these..."
    explanation?: string; // Why products fit
    next_page_offset: number | null; // For "Load More"
}

export interface CartActionResponse {
    response_type: 'cart_action';
    action: 'add';
    product_id: string;
    variant_id: string;
    product_title: string;
    acknowledgement: string;
}

export interface CartSummaryResponse {
    response_type: 'cart_summary';
    items: Array<{
        product_id: string;
        variant_id: string;
        title: string;
        price: string;
        quantity: number;
    }>;
    subtotal: string;
    shipping: string;
    tax: string;
    total: string;
    currency: string;
    acknowledgement: string;
    draft_order_id?: string;
}

export interface OrderPlacedResponse {
    response_type: 'order_placed';
    order_id: string;
    order_number: string;
    total: string;
    currency: string;
    acknowledgement: string;
}

export interface ImageGenerationResponse {
    response_type: 'image_generation';
    intent_id: string;
    outcome_description: string;
    images: Array<{
        url: string;
        variant_id: string;
        caption: string;
        interpretation: string;
    }>;
    cached_products?: any[]; // Phase 4: Pre-fetched products
    acknowledgement: string;
    explanation: string;
}

export type BackendResponse = ClarificationResponse | RecommendationResponse | CartActionResponse | CartSummaryResponse | OrderPlacedResponse | ImageGenerationResponse;

// ============================================================================
// REQUEST VALIDATION (Prevent Malformed Requests)
// ============================================================================

function validateChatRequest(payload: ChatRequest): void {
    // Must have session_id
    if (!payload.session_id || typeof payload.session_id !== 'string') {
        throw new Error('session_id required');
    }

    // Must have non-empty current_message
    if (!payload.current_message || payload.current_message.trim() === '') {
        throw new Error('current_message cannot be empty');
    }

    // chat_history must be array
    if (!Array.isArray(payload.chat_history)) {
        throw new Error('chat_history must be array');
    }

    // Each history item must have role and content only
    payload.chat_history.forEach((msg, idx) => {
        if (!msg.role || !msg.content) {
            throw new Error(`chat_history[${idx}] missing role or content`);
        }
        if (msg.role !== 'user' && msg.role !== 'assistant') {
            throw new Error(`chat_history[${idx}] invalid role: ${msg.role}`);
        }
        // Ensure no extra fields (prevent metadata leakage)
        const allowedKeys = ['role', 'content'];
        Object.keys(msg).forEach(key => {
            if (!allowedKeys.includes(key)) {
                throw new Error(`chat_history[${idx}] has unexpected field: ${key}`);
            }
        });
    });
}

// ============================================================================
// BACKEND API
// ============================================================================

export async function sendMessageToBackend(
    payload: ChatRequest
): Promise<BackendResponse> {
    // Validate request before sending
    console.log('📡 sending message to backend:', payload);
    validateChatRequest(payload);

    try {
        console.log('📡 fetch url:', config.backend.apiUrl);
        const response = await fetch(config.backend.apiUrl, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(payload),
        });

        if (!response.ok) {
            throw new Error(`Backend error: ${response.status} ${response.statusText}`);
        }

        const data = await response.json();

        // Validate response type
        if (!data.response_type ||
            (data.response_type !== 'clarification' &&
                data.response_type !== 'recommendation' &&
                data.response_type !== 'cart_action' &&
                data.response_type !== 'cart_summary' &&
                data.response_type !== 'order_placed' &&
                data.response_type !== 'image_generation')) {
            console.error('Invalid response from backend:', data);
            throw new Error(`Invalid response_type from backend: ${data.response_type || 'undefined'}`);
        }

        return data as BackendResponse;
    } catch (error) {
        // Re-throw with context
        if (error instanceof Error) {
            throw new Error(`Backend communication failed: ${error.message}`);
        }
        throw new Error('Backend communication failed: Unknown error');
    }
}

// ============================================================================
// SHOPIFY CART API
// ============================================================================

export interface AddToCartRequest {
    id: string; // variant_id
    quantity: number;
}

export async function addToShopifyCart(
    variantId: string
): Promise<void> {
    try {
        const response = await fetch('/api/shopify', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                action: 'add_to_cart',
                params: {
                    payload: {
                        items: [
                            {
                                id: Number(variantId),
                                quantity: 1
                            }
                        ]
                    }
                }
            }),
        });

        if (!response.ok) {
            const errorData = await response.json();
            throw new Error(`Shopify error: ${response.status} - ${errorData.details || response.statusText}`);
        }

        // Success - cart updated
    } catch (error) {
        if (error instanceof Error) {
            throw new Error(`Failed to add to cart: ${error.message}`);
        }
        throw new Error('Failed to add to cart: Unknown error');
    }
}
