import { supabase } from '@/lib/supabase';

export interface EnrichedProduct {
    id: string;
    title: string;
    price: string;
    image_url: string;
    highlights?: string[];
    fit_score?: number;
    score_breakdown?: any;
}

// Fetch top products for a given intent, enriched with scores.
export async function getTopProducts(intentId: string, offset = 0, limit = 3): Promise<EnrichedProduct[]> {
    // Get scores
    const { data: scores, error } = await supabase
        .from('product_intent_scores')
        .select('product_id, fit_score, score_breakdown')
        .eq('intent_id', intentId)
        .order('fit_score', { ascending: false })
        .range(offset, offset + limit - 1); // Pagination: inclusive range
    if (error) throw new Error('Failed to fetch product scores');

    const productIds = (scores as any).map((s: any) => s.product_id);

    // Get product details
    // Note: products_raw schema seems to mirror Shopify structure (variants, images, etc.)
    // We select '*' to get all fields including variants and images JSON
    const { data: products, error: prodErr } = await supabase
        .from('products_raw')
        .select('*')
        .in('id', productIds);
    if (prodErr) throw new Error('Failed to fetch product details');

    // Merge
    return productIds.map((id: string) => {
        const prod = (products as any).find((p: any) => p.id === id);
        const score = (scores as any).find((s: any) => s.product_id === id);

        // Robust extraction for Shopify-like schema
        const price = prod.variants?.[0]?.price || "N/A";
        const image_url = prod.images?.[0]?.src || "";
        const highlights: string[] = []; // Highlights not in DB, will be generated by LLM if needed

        return {
            id: prod.id,
            title: prod.title,
            price: price,
            image_url: image_url,
            highlights: highlights,
            fit_score: score?.fit_score,
            score_breakdown: score?.score_breakdown,
        } as EnrichedProduct;
    });
}
